lsi:            false
exclude:        ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md", "scss"]
permalink:      /writing/:title
markdown_ext:   markdown,mkd,mkdn,md
name:           alms.io website
description:    "The business website for alms.io."
url:            http://alms.io
sass:
  sass_dir: _sass
  style: compressed
